// Uygulama genelinde kullanilan hata kod sabitleri
export const ERROR_CODES = {
  USER_EXISTS: 'USER_EXISTS',
  USER_CREATE_FAILED: 'USER_CREATE_FAILED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  UNAUTHORIZED: 'UNAUTHORIZED',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
  TOKEN_REVOKED: 'TOKEN_REVOKED',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  PRODUCT_CREATE_FAILED: 'PRODUCT_CREATE_FAILED',
  PRODUCT_IMAGE_NOT_FOUND: 'PRODUCT_IMAGE_NOT_FOUND',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  TOO_MANY_IMAGES: 'TOO_MANY_IMAGES',
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  CATEGORY_EXISTS: 'CATEGORY_EXISTS',
  CATEGORY_HAS_PRODUCTS: 'CATEGORY_HAS_PRODUCTS',
  CATEGORY_CREATE_FAILED: 'CATEGORY_CREATE_FAILED',
  SKU_EXISTS: 'SKU_EXISTS',
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  INVALID_STOCK_QUANTITY: 'INVALID_STOCK_QUANTITY',
  STOCK_MOVEMENT_FAILED: 'STOCK_MOVEMENT_FAILED',
  INVALID_UNIT: 'INVALID_UNIT',
} as const

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]
